version: 1

build:
  type: python
  dockerfile: Dockerfile  # Optional, if not provided, defaults to "Dockerfile"
  upload_artifacts: true

release:
  rolling: false
  on_tag: true # Optional, if not provided, defaults to true
  create_github_release: false # Defaults to false

deploy:
  gitops:
    enable: false
    repository: "notarock/gitops"
    manifest: "traduirbot/deployment.yaml"
