name: Create and publish a Docker image
run-name: "Publish docker image [${{ github.ref_name }}]"

on:
  push:
    tags:
      - "*"

jobs:
  release:
    uses: notarock/tuyauterie/.github/workflows/ImageAutoRelease.yml@main
    secrets:
      REGISTRY_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
  rolling-deploy:
    needs: [release]
    uses: notarock/tuyauterie/.github/workflows/UpdateDeploymentVersion.yml@main
    with:
      version: ${{ needs.release.outputs.version }}
      repository: "notarock/gitops"
      deployment-path: "traduir/traduirbot-deployment.yaml"
    secrets:
      gitops-token: ${{ secrets.GITOPS_TOKEN }}
